/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
/**
 *
 * @author HARSHIT
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setSize(1000,700);
        setLocationRelativeTo(null);
        fc1.setVisible(false);
        fc2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc2 = new javax.swing.JFileChooser();
        bt1 = new javax.swing.JButton();
        tf2 = new javax.swing.JTextField();
        lb1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fc1 = new javax.swing.JFileChooser();
        tf1 = new javax.swing.JTextField();
        bt2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        fc2.setApproveButtonText("Copy here");
        fc2.setCurrentDirectory(new java.io.File("D:\\"));
            fc2.setDialogTitle("Choose destination directory");
            fc2.setFileHidingEnabled(true);
            fc2.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
            fc2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            fc2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    fc2ActionPerformed(evt);
                }
            });
            getContentPane().add(fc2);
            fc2.setBounds(140, 300, 200, 190);

            bt1.setText("Click here to choose a file");
            bt1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bt1ActionPerformed(evt);
                }
            });
            getContentPane().add(bt1);
            bt1.setBounds(50, 60, 155, 23);

            tf2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    tf2ActionPerformed(evt);
                }
            });
            getContentPane().add(tf2);
            tf2.setBounds(280, 170, 460, 23);

            lb1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
            lb1.setText("File to be Copied");
            getContentPane().add(lb1);
            lb1.setBounds(50, 20, 160, 30);

            jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
            jLabel1.setText("Destination Directory");
            getContentPane().add(jLabel1);
            jLabel1.setBounds(50, 110, 210, 40);

            fc1.setApproveButtonText("Copy here");
            fc1.setControlButtonsAreShown(false);
            fc1.setCurrentDirectory(new java.io.File("D:\\"));
                fc1.setDialogTitle("Choose a file to be Copied");
                getContentPane().add(fc1);
                fc1.setBounds(420, 330, 180, 150);

                tf1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        tf1ActionPerformed(evt);
                    }
                });
                getContentPane().add(tf1);
                tf1.setBounds(280, 60, 460, 23);

                bt2.setText("Choose desination");
                bt2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        bt2ActionPerformed(evt);
                    }
                });
                getContentPane().add(bt2);
                bt2.setBounds(60, 170, 120, 23);

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void fc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fc2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        fc1.setVisible(true);
        int r = fc1.showOpenDialog(this);
        if(r==JFileChooser.APPROVE_OPTION)
        {
            tf1.setText(fc1.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        fc2.setVisible(true);
        int r = fc2.showOpenDialog(this);
        if(r==JFileChooser.APPROVE_OPTION)
        {
            tf2.setText(fc2.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JFileChooser fc1;
    private javax.swing.JFileChooser fc2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
